---
name: CI
on:
  schedule:
    # run every Saturday
    - cron: "0 12 * * 6"
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: [1.18.x]

    name: Test with Go ${{ matrix.go }}
    runs-on: ubuntu-18.04

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Tidy
      run: go mod tidy

    - name: Install
      run: go install -v ./...

    - name: Test
      run: go test -v -coverprofile=cover.out -covermode=count ./...
      env:
        RTM_TEST_KEY:    ${{ secrets.RTM_TEST_KEY }}
        RTM_TEST_SECRET: ${{ secrets.RTM_TEST_SECRET }}
        RTM_TEST_TOKEN:  ${{ secrets.RTM_TEST_TOKEN }}

    - name: Upload coverage report
      run: curl -s https://codecov.io/bash | bash -s -- -X fix
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
